### ISSUE TITLE
Splash Window

### ISSUE THREAD

**Issue by mrodz** [mrodz/coderz#1]
Create a splash (loading) window to show while the React UI is loading.
- [x] `public/splash.html` - `@keyframes` animations to make a spinner, minimalistic design.
- [x] Create a function in `src/App.tsx` that will send a message via the electron bridge to remove the splash window (`useEffect`).
- [x] Create a function in `public/bridge-functions.js` to receive notice of DOM rendering and remove the splash window.
## Todo
- work with dark/light mode.

**Comment by mrodz** [comment]
done!
